language: node_js
node_js:
    - "6.9.0"
    - "8.5.0"

install:
    - npm install .
    - npm install kelda/deployment-engine-downloader && ./node_modules/.bin/kelda-downloader

before_script:
    - npm install -g gulp-cli

script:
    - gulp lint test
    - mkdir -p ~/.kelda/infra/ && mv ./testInfra.js ~/.kelda/infra/default.js
    - ./kelda inspect ./haproxyAutoHttps.js graphviz
    - ./kelda inspect ./examples/haproxyHttpsExample.js graphviz

notifications:
    slack:
        secure: A6AW5xc9wkqid8Qv4MMGXazLfXI4SCIq7OTyCNrZuqsUXaNSebB8DDi5jq1cfVEwQlz5t/pq9iIoGA889qmkYBM/ulf36z/S2sXHPNCVIQYIbGjKEFzRMsdcmS5nAHUM+rKg6YzHHFpZAVWcQGW7M511g2cEcMbXrio5uaNDnJFea0UegoSpfkNkj+UlouF5LvrZSyJR/O0COyumRaapGRQmXLtoEygmNY6DgKoR4Vb6xLs4uAjsXcyY1UhPTQDdR5DTVVh3/Z2NPkQsb7LFydODQbPOcBomfWDzx0Efdm+LnxeQWGX2yWB23vivuIIEaN/LQhaXs+ru+huBpEReD5LSh0G3gbQoMTatbJyFpxGDDn3gJPNP/GzFgrGTYX0Ft+d5hxBe7Bb8m2LLFq4k/oKGtmGq9HI+4/uPEEDjn1Pv6iaeic1L8GWN/EhuF9hHvsNtsGHg8Xp8q0FG7MgdUWC3Tk0hh5W09gD9mskCa1qp0I7C13hkTIyLx2/s6l7m+qai5HEBhK5+t3KdnuRUtyG+s2cm3022//2FAJppMlLYuJjluDoG0+WACpUGtOvYfn/uEsFwD6kzrSveqm+WdEEweEy5IG9XduUUXWVcN8qutS8SfVYyS0joIIJDMD7jA7/hpLIniNQuRm3fA3oSVJPsSpy8XfQ0zPrVpj9C+dA=
